"""Public Stage 5A perception detection-contract API."""

from football_analytics.perception.contracts import (
    CONTRACT_NAMES,
    DETECTIONS_CONTRACT,
    DETECTIONS_VERSION,
    JSON_SCHEMA_NAMES,
    assert_detection_contracts_registered,
    compile_detection_schemas,
    detection_schema_fingerprints,
    load_all_detection_contracts,
    load_detection_contract,
    load_perception_json_schema,
    validate_against_json_schema,
)
from football_analytics.perception.policy import (
    load_detection_policy,
    policy_fingerprint,
    resolve_frame_routing,
)
from football_analytics.perception.taxonomy import (
    ClassMappingResult,
    load_detection_taxonomy,
    map_model_class,
    taxonomy_fingerprint,
)
from football_analytics.perception.transforms import (
    build_preprocessing_transform,
    clip_bbox_xyxy,
    forward_bbox,
    inverse_bbox,
    roundtrip_bbox,
    validate_bbox_xyxy,
)
from football_analytics.perception.types import (
    CONTRACT_VERSION,
    ERROR_CODES,
    PROCESSED_STATUSES,
    UNPROCESSED_STATUSES,
    ChannelOrder,
    ColorSpace,
    DetectionAttributes,
    DetectionFrameStatus,
    DetectionRunReceipt,
    Eligibility,
    EntityType,
    Orientation,
    PerceptionContractError,
    PerceptionError,
    PreprocessingTransform,
    ProcessingStatus,
    ReceiptStatus,
    ResizeMode,
    ReviewStatus,
    RoleLabel,
    RoleSource,
)
from football_analytics.perception.validation import validate_detection_bundle

__all__ = [
    "CONTRACT_VERSION",
    "CONTRACT_NAMES",
    "DETECTIONS_CONTRACT",
    "DETECTIONS_VERSION",
    "JSON_SCHEMA_NAMES",
    "ERROR_CODES",
    "PROCESSED_STATUSES",
    "UNPROCESSED_STATUSES",
    "PerceptionError",
    "PerceptionContractError",
    "EntityType",
    "RoleLabel",
    "RoleSource",
    "ProcessingStatus",
    "Eligibility",
    "ReviewStatus",
    "ResizeMode",
    "ReceiptStatus",
    "ColorSpace",
    "ChannelOrder",
    "Orientation",
    "DetectionFrameStatus",
    "DetectionAttributes",
    "PreprocessingTransform",
    "DetectionRunReceipt",
    "ClassMappingResult",
    "load_detection_contract",
    "load_all_detection_contracts",
    "detection_schema_fingerprints",
    "compile_detection_schemas",
    "assert_detection_contracts_registered",
    "load_perception_json_schema",
    "validate_against_json_schema",
    "load_detection_taxonomy",
    "taxonomy_fingerprint",
    "map_model_class",
    "load_detection_policy",
    "policy_fingerprint",
    "resolve_frame_routing",
    "validate_bbox_xyxy",
    "clip_bbox_xyxy",
    "build_preprocessing_transform",
    "forward_bbox",
    "inverse_bbox",
    "roundtrip_bbox",
    "validate_detection_bundle",
]
