"""Public Stage 4 broadcast contract + routing API."""

from football_analytics.broadcast.contracts import (
    CONTRACT_NAMES,
    assert_broadcast_contracts_registered,
    broadcast_schema_fingerprints,
    compile_broadcast_schemas,
    load_all_broadcast_contracts,
    load_broadcast_contract,
)
from football_analytics.broadcast.types import (
    CONTRACT_VERSION,
    NON_PLAYABLE_VIEW_FAMILIES,
    AnalysisWindow,
    BroadcastContractError,
    BroadcastError,
    CameraMotion,
    CameraPosition,
    CameraViewSegment,
    ClassificationSource,
    DetectionSource,
    Eligibility,
    FramingScale,
    GraphicsStatus,
    MappingQuality,
    Playability,
    ReplayStatus,
    ReviewStatus,
    SegmentStatus,
    ShotBoundary,
    ShotSegment,
    Suitability,
    TransitionType,
    ViewFamily,
)
from football_analytics.broadcast.validation import (
    validate_analysis_windows_bundle,
    validate_broadcast_bundle,
)

__all__ = [
    "CONTRACT_VERSION",
    "CONTRACT_NAMES",
    "BroadcastError",
    "BroadcastContractError",
    "TransitionType",
    "DetectionSource",
    "ReviewStatus",
    "SegmentStatus",
    "ViewFamily",
    "FramingScale",
    "CameraPosition",
    "CameraMotion",
    "ReplayStatus",
    "GraphicsStatus",
    "Playability",
    "Suitability",
    "Eligibility",
    "ClassificationSource",
    "NON_PLAYABLE_VIEW_FAMILIES",
    "MappingQuality",
    "ShotBoundary",
    "ShotSegment",
    "CameraViewSegment",
    "AnalysisWindow",
    "load_broadcast_contract",
    "load_all_broadcast_contracts",
    "broadcast_schema_fingerprints",
    "compile_broadcast_schemas",
    "assert_broadcast_contracts_registered",
    "validate_broadcast_bundle",
    "validate_analysis_windows_bundle",
]
